### ISSUE TITLE
In Example Log.Formatter is useless

### ISSUE THREAD

**Issue by melonwool** [rifflock/lfshook#21]
In example use  Log.Formatter = new(log.JSONFormatter) , but in lfshook.go ,  NewHook function  use txtFormatter, and  at  line 138 use  hook.formatter.Format(entry) .  Must I use SetFormatter to replace the formatter

**Comment by rifflock** [comment]
Oh, good catch. Yeah, that example is wrong.

I updated the documentation. Also corrected the import path.

Really for the setup of the logger itself you should defer to the documentation in the parent project:
https://github.com/sirupsen/logrus

They're actively maintaining and updating there.
