### ISSUE TITLE
Use of "v" in version tag to support gopkg.in

### ISSUE THREAD

**Issue by mnordsletten** [rifflock/lfshook#26]
The version tags up to version 1.3 use the `v1.3` semantic, but from there on the use of the `v` is removed. 

This breaks compatibility with [gopkg.in](http://labix.org/gopkg.in) that we were trying to utilize now that the breaking change that came with 2.0 was implemented. 

[only v.1 is supported in gopkg](http://gopkg.in/rifflock/lfshook.v1)

If there is a good reason for removing the `v` then we'll have to figure out a different way to ensure versioning of our dependencies.

**Comment by rifflock** [comment]
There was no good reason for removing it. I've been writing a lot of node lately and we were using versions without the `v` and I think I switched subconsciously. Let me fix that.

**Comment by rifflock** [comment]
I've updated all releases to start with a `v`. It occurs to me that making that change might cause problems for other people since I modified a bunch of existing releases instead of creating new ones...

**Comment by mnordsletten** [comment]
Thanks. This solves it for our use case. Hopefully it didn't break for anyone else. I'll close the issue.
