### ISSUE TITLE
Can't create log files in JSON format

### ISSUE THREAD

**Issue by kafan1986** [rifflock/lfshook#29]
I am using below code to log. Although the console output is JSON formatted but the log files created have text format. Can you point out what am I missing here?

`
       logwriter, err := rotatelogs.New(path+"go.log.%Y%m%d%H%M",
		rotatelogs.WithLinkName("goUtilitySectionLogs.current"),
		rotatelogs.WithRotationTime(time.Hour),
		rotatelogs.WithMaxAge(7*24*time.Hour),
	)

	if err != nil {
		fmt.Println("Error in initializing logging service - GoUtilitySectionLogs ", err)
	}

	// Log as JSON instead of the default ASCII formatter.
	log.Formatter = new(logrus.JSONFormatter)
	// Output to stderr instead of stdout, could also be a file.
	log.Out = os.Stdout
	// Only log the warning severity or above.
	log.Level = logrus.InfoLevel //logrus.DebugLevel
	//Adding a hook to direct the console output to logwriter
	log.Hooks.Add(lfshook.NewHook(lfshook.WriterMap{logrus.InfoLevel: logwriter, logrus.ErrorLevel: logwriter}))`

**Comment by rifflock** [comment]
Are you passing your formatter to the constructor of lfshook?

There was a lot of back and forth on how this hook should behave, and eventually it was determined that the formatter of the lfshook would need to be set explicitly (see #24), so if you were to instead do:

```
formatter := new(logrus.JSONFormatter)
// Log as JSON instead of the default ASCII formatter.
log.Formatter = formatter
...
log.Hooks.Add(lfshook.NewHook(lfshook.WriterMap{logrus.InfoLevel: logwriter, logrus.ErrorLevel: logwriter}, formatter))
```
It _should_ work as expected.

**Comment by kafan1986** [comment]
I already tried this earlier by looking at your examples but it is giving me this error. 

too many arguments in call to lfshook.NewHook have (lfshook.WriterMap, *logrus.JSONFormatter)    want (interface {})

**Comment by rifflock** [comment]
Are you running version `v2.x`? That error suggests that you're running a version below `v2.0`. Looking at the code the constructor has two parameters. The error suggests that it only wants one parameter, which was the case in the last major revision.

**Comment by kafan1986** [comment]
Got it. Thanks.
