### ISSUE TITLE
Failed to fire hook 

### ISSUE THREAD

**Issue by Vikash082** [rifflock/lfshook#32]
I haven't created '/var/log/test.log' file. I got below error:
Failed to fire hook: open /var/log/test.log: permission denied

However, after creating file and assigning proper permission things worked fine.

Is this the intended behaviour ?

**Comment by rifflock** [comment]
If your `/var/log` directory already existed and the app didn't have the permissions to write to that directory then yes, that's the correct behavior.

It runs a `MkdirAll` which will create the directory structure if it doesn't already exist and correctly set the permissions for the directory (assuming the app has the right permissions to create that folder structure).

If the path already exists, then no changes are made, so it would be worthwhile to check and see if everything works if the file is not created, but the app has write permissions to `/var/log`.

The call to `OpenFile` with the `os.CREATE` flag set should create the file if it doesn't exist.
