### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by brunomilani** [rifflock/lfshook#34]
Hi Rifflock, Can you show a use example of this package? I'm bit confuse to use this in global scope in my go application. Thank you!

**Comment by rifflock** [comment]
Hey @brunomilani, this package is just a hook for [logrus](https://github.com/sirupsen/logrus) and has no functionality on its own. You would define a logrus implementation in the global scope, and then add `lfshook` as one of the hooks that it writes to. There's a description of how to this in the README (though the README is slightly out of date. There's an open issue #30 to update it)
