### ISSUE TITLE
Is it not efficient that open/close file each time while logrus fires hook writing?

### ISSUE THREAD

**Issue by ryanking8215** [rifflock/lfshook#39]
I read the source code, found that every time user invoke logrus to log, then logrus fires hook writing, lfshook opens file , writes message and closes it. 

why not keep it opened? Is it not efficient such way?

**Comment by rifflock** [comment]
Hey Ryan,

When I was first learning golang a few years back it was explicitly stated in the documentation that leaving file descriptors open is bad practice. Having an open file locks the file, so any other process that tries to access that file would be locked out until the handler was released.

I don't use Go that much anymore, so I don't know if that has changed, but afaik it's still best practice not to leave a reference to a file open when not actively accessing it.
