### ISSUE TITLE
Logging to file doesn't persist the stdout formatter unless it is of type TextFormatter

### ISSUE THREAD

**Issue by mattrgreen** [rifflock/lfshook#6]
The introduction of:

```
//switch to TextFormatter
formatter := entry.Logger.Formatter
entry.Logger.Formatter = txtFormatter
defer func() {
    // assign back original formatter
    entry.Logger.Formatter = formatter
}()
```

Means logging to files using the JSONFormatter is no longer possible as we are forced to use the default:

`var txtFormatter = &logrus.TextFormatter{DisableColors: true}`

**Comment by rifflock** [comment]
Good change, thanks for the PR. I'm updating the version now.

**Comment by rifflock** [comment]
fixed in https://github.com/rifflock/lfshook/releases/tag/v1.2
